apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: spring1
  labels:
    run: spring1
spec:
  type: NodePort 
  ports:
  - nodePort: 30125
    port: 8080
    protocol: TCP
  selector:
    run: spring1
